parallel-jobs = 1
enable-module-update = true
remove-rv-integrations-checks = true

[YouTube]
enabled = true
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music]
enabled = true
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Google-Photos]
enabled = true
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[Duolingo]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/duolingo/duolingo-duolingo"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.duolingo"

[Twitch]
enabled = false 
# arch = "all"
# version = "25.3.0"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[Twitter]
enabled = false 
# arch = "all"
# version = "10.86.0-release.0"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[TikTok]
enabled = false 
# arch = "all"
# version = "auto"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"

[Google-Recorder]
enabled = true 
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"

[Proton-Mail]
enabled = true 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
# archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[Proton-VPN]
enabled = true
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"

[Samsung-Radio]
enabled = true 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://samsung-radio.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.sec.android.app.fm"

[Lightroom]
enabled = true
arch = "arm64-v8a"
version = "auto"
patches-source = "ReVanced/revanced-patches"
# uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"

[Spotify]
enabled = false 
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.spotify.music"

[Reddit]
enabled = false
patches-source = "ReVanced/revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[Twitter-Piko]
enabled = false 
app-name = "Twitter"
arch = "both"
rv-brand = "ReVanced-Piko"
patches-source = "crimera/piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
build-mode = "both"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Extended]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Reddit-Extended]
enabled = false 
app-name = "Reddit"
rv-brand = "ReVanced-Extended"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[YouTube-Advanced]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-Advanced]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Reddit-Advanced]
enabled = false 
app-name = "Reddit"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[Spotify-Advanced]
enabled = false 
app-name = "Spotify"
rv-brand = "ReVanced-Advanced"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.spotify.music"

[YouTube-LisoUseInAIKyrios]
enabled = true
app-name = "YouTube"
build-mode = "both"
rv-brand = "ReVanced-LisoUseInAIKyrios"
cli-source = "LisoUseInAIKyrios/revanced-cli"
patches-source = "LisoUseInAIKyrios/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[YouTube-Music-LisoUseInAIKyrios]
enabled = true
app-name = "YouTube-Music"
build-mode = "both"
arch = "both"
rv-brand = "ReVanced-LisoUseInAIKyrios"
cli-source = "LisoUseInAIKyrios/revanced-cli"
patches-source = "LisoUseInAIKyrios/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Gboard-ReVanced-Privacy]
enabled = false
app-name = "Gboard"
rv-brand = "ReVanced-Privacy"
build-mode = "both"
arch = "both"
patches-source = "jkennethcarino/privacy-revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
# archive-dlurl = ""

[youtube-rvx-morphed]
enabled = true
app-name = "youtube"
rv-brand = "rvx-morphed"
build-mode = "both"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
excluded-patches = "'Overlay buttons', 'Change splash icons', 'Restore old seekbar thumbnails'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-rvx-morphed]
enabled = true
app-name = "youtube-music"
rv-brand = "rvx-morphed"
build-mode = "both"
arch = "both"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe-Extended]
enabled = false 
app-name = "Reddit"
rv-brand = "Morphe-Extended"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"
