parallel-jobs = 1
patches-version = "latest"
enable-magisk-update = true
remove-rv-integrations-checks = true

[youtube-rvx]
enabled = true
app-name = "youtube"
rv-brand = "rvx"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-rvx]
enabled = true
app-name = "youtube-music"
rv-brand = "rvx"
build-mode = "both"
arch = "both"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-rvx]
enabled = true 
app-name = "reddit"
rv-brand = "rvx"
patches-source = "inotia00/revanced-patches"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[google-photos-revanced]
enabled = true
app-name = "google-photos"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
patches-version = "v5.50.0-dev.7"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"
