patches-version = "dev"
cli-version = "dev"
enable-magisk-update = false
parallel-jobs = 1

[youtube-revanced]
enabled = true
app-name = "youtube"
rv-brand = "revanced"
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-revanced]
enabled = true
app-name = "youtube-music"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[google-photos-revanced]
enabled = false
app-name = "google-photos"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[youtube-anddea]
enabled = false
app-name = "youtube"
rv-brand = "anddea"
build-mode = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea]
enabled = false
app-name = "youtube-music"
rv-brand = "anddea"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-anddea]
enabled = false 
app-name = "reddit"
rv-brand = "anddea"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[spotify-anddea]
enabled = false 
app-name = "spotify"
rv-brand = "anddea"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-durl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.spotify.music"

[twitter-piko]
enabled = false 
app-name = "twitter"
rv-brand = "piko"
arch = "both"
build-mode = "both"
patches-source = "crimera/piko"
patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# dpi = "120-640dpi 480dpi nodpi anydpi"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[youtube-morphe]
enabled = false
app-name = "youtube"
rv-brand = "morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-morphe]
enabled = false
app-name = "youtube-music"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-morphe]
enabled = false
app-name = "reddit"
rv-brand = "morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[youtube-rvx-morphed]
enabled = false
app-name = "youtube"
rv-brand = "rvx-morphed"
build-mode = "both"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-rvx-morphed]
enabled = false
app-name = "youtube-music"
rv-brand = "rvx-morphed"
build-mode = "both"
arch = "both"
patches-source = "wchill/rvx-morphed"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"



