parallel-jobs = 1
patches-version = "latest"
# cli-version = "dev"
enable-magisk-update = true

[twitter-piko-materialu]
enabled = true 
app-name = "twitter"
rv-brand = "piko-materialu"
arch = "both"
patches-source = "crimera/piko"
included-patches = "'Bring back twitter' 'Dynamic color'"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
