parallel-jobs = 1
patches-version = "dev"
# cli-version = "dev"
enable-magisk-update = false

[youtube-revanced]
enabled = true
app-name = "youtube"
rv-brand = "revanced"
build-mode = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-revanced]
enabled = true
app-name = "youtube-music"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[google-photos-revanced]
enabled = true
app-name = "google-photos"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[google-recorder-revanced]
enabled = true 
app-name = "google-recorder"
rv-brand = "revanced"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
dpi = "480-640dpi 120-640dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.recorder"

[proton-vpn-revanced]
enabled = true
app-name = "proton-vpn"
rv-brand = "revanced"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"

[messenger-revanced]
enabled = true
app-name = "messenger"
rv-brand = "revanced"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
dpi = "360-480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger"

[twitter-piko]
enabled = false 
app-name = "twitter"
rv-brand = "piko"
arch = "both"
build-mode = "both"
patches-source = "crimera/piko"
patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"
