name: Cleanup

on:
  schedule:
    - cron: "20 4 1 * *" # 04:20 AM UTC on day 1 of every month
  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    timeout-minutes: 10
    steps:
      - name: Delete Older Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 500
          delete_workflows: true
          workflows_keep_day: 30
          gh_token: ${{ secrets.GITHUB_TOKEN }}
