name: Cleanup

on:
  workflow_dispatch:

concurrency:
  group: clean
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    timeout-minutes: 10
    steps:
      - name: Delete Older Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 100
          delete_workflows: true
          workflows_keep_day: 7
          releases_keep_keyword: stable/beta
          gh_token: ${{ secrets.GITHUB_TOKEN }}
