name: Sync

on:
  schedule:
    - cron: "20 16 * * *" # 04:20 PM UTC everyday
  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: nvbangg/revanced-morphe-builder

          
